# Generated by Django 2.1.2 on 2018-11-28 18:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_therapy', '0002_auto_20181123_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_therapy',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
