# Generated by Django 2.1.2 on 2018-12-01 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group_therapy', '0003_auto_20181128_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_therapy',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
    ]
