# Generated by Django 2.1.2 on 2018-11-28 19:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_service',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
