# Generated by Django 2.1.2 on 2018-11-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['name'], 'verbose_name': 'enlace', 'verbose_name_plural': 'enlaces'},
        ),
        migrations.AlterField(
            model_name='link',
            name='ulr',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
    ]
