# Generated by Django 2.1.2 on 2018-11-28 18:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgtb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgtb',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
