# Generated by Django 2.1.2 on 2018-11-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_therapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_therapy',
            name='image',
            field=models.ImageField(upload_to='individual_therapy', verbose_name='Imágen'),
        ),
    ]
