# Generated by Django 2.1.2 on 2018-11-30 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('individual_therapy', '0003_auto_20181127_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_therapy',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
    ]
