# Generated by Django 2.1.2 on 2018-12-01 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teenagers_therapy', '0002_auto_20181128_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='teenagers_therapy',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
    ]
