# Generated by Django 2.1.2 on 2018-11-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrens_therapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrens_therapy',
            name='image',
            field=models.ImageField(upload_to='childrens_therapy', verbose_name='Imágen'),
        ),
    ]
