# Generated by Django 2.1.2 on 2018-12-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childrens_therapy', '0004_childrens_therapy_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childrens_therapy',
            options={'ordering': ['-created'], 'verbose_name': 'terapia para niños', 'verbose_name_plural': 'terapias para niños'},
        ),
    ]
